cmake_minimum_required(VERSION 3.30)
project(CSES)

set(CMAKE_CXX_STANDARD 14)

add_executable(CSES
    CSES/CSES_Apartments.cpp
    CSES/CSES_Apple_Division.cpp
    CSES/CSES_Bit_Strings.cpp
    CSES/CSES_Chessboard_And_Queens.cpp
    CSES/CSES_Coin_Piles.cpp
    CSES/CSES_Concert_Tickets.cpp
    CSES/CSES_Creating_Strings.cpp
    CSES/CSES_Digit_Queries.cpp
    CSES/CSES_Distinct_Numbers.cpp
    CSES/CSES_Ferris_Wheel.cpp
    CSES/CSES_Gray_Code.cpp
    CSES/CSES_Increasing_Array.cpp
    CSES/CSES_Maximum_Subarray_Sum.cpp
    CSES/CSES_Missing_Number.cpp
    CSES/CSES_Movie_Festival.cpp
    CSES/CSES_Number_Spiral.cpp
    CSES/CSES_Palindrome_Reorder.cpp
    CSES/CSES_Permutations.cpp
    CSES/CSES_Repetitions.cpp
    CSES/CSES_Restaurant_Customers.cpp
    CSES/CSES_Sum_Of_Two_Values.cpp
    CSES/CSES_Trailing_Zeros.cpp
    CSES/CSES_Two_Knights.cpp
    CSES/CSES_Two_Sets.cpp
    CSES/CSES_Weird_Algorithm.cpp
        CSES/CSES_Stick_Lengths.cpp
        CSES/CSES_Collecting_Numbers.cpp
        CSES/CSES_Collecting_Numbers_2.cpp
        CSES/CSES_Playlist.cpp
)

